// Generated by scripts/generate-pronunciations.mjs (npm run audio) — do not edit by hand.
// The clips in public/audio/vi/<slug>.m4a. A phrase listed here is played from its file on every device; any other
// phrase falls back to the browser's own Vietnamese voice, and its speaker button stays hidden if the device has none.
import { slugify } from "./slug";

export { slugify };

export const recorded = new Set<string>([
  "cao-son-truong-thuy",
  "ha-son-nhap-thuy",
  "moi-tra",
  "ngoc-diep-hoi-cung",
  "nhat-thuy-nhi-tra-tam-boi-tu-binh-ngu-quan-anh",
  "rot-deu",
  "tam-long-gia-ngoc",
  "tra-dau-xuan",
  "tra-den",
  "tra-man",
  "tra-nhai",
  "tra-o-long",
  "tra-sen",
  "tra-shan-tuyet",
  "tra-xanh",
  "trang-tra",
  "xem-ngui-pham",
]);
